#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR" -cp "$APPDIR/lib/savie_movie_6.jar:$APPDIR/lib/core.jar:$APPDIR/lib/video.jar:$APPDIR/lib/jl1.0.jar:$APPDIR/lib/minim.jar:$APPDIR/lib/mp3spi1.9.4.jar:$APPDIR/lib/tritonus_aos.jar:$APPDIR/lib/tritonus_share.jar" savie_movie_6
